import { LockKeyhole, LogOut } from 'lucide-react';

export default function AccountView({ onNotify }: { onNotify: (message: string) => void }) {
  return (
    <div className="space-y-4">
      <section className="rounded-lg border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-4"><span className="flex h-14 w-14 items-center justify-center rounded-full bg-sky-100 text-lg font-bold text-brand">VA</span><div><h2 className="text-xl font-bold text-slate-900">BS. Nguyễn Văn A</h2><p className="mt-1 text-sm text-slate-500">Khoa Tai Mũi Họng | Mã NS: DR-019</p></div></div></section>
      <section className="grid gap-4 xl:grid-cols-2">
        <article className="panel"><h3 className="mb-4 text-base font-bold text-slate-800">Bảo mật & Cài đặt</h3><div className="space-y-3"><label><span className="mb-1.5 block text-sm font-medium text-slate-700">Đổi mật khẩu</span><input className="form-input" placeholder="Nhập mật khẩu hiện tại" type="password" /></label><input className="form-input" placeholder="Nhập mật khẩu mới" type="password" /><button type="button" onClick={() => onNotify('Đã lưu mật khẩu mới')} className="secondary-action cursor-pointer active:scale-[0.98]"><LockKeyhole size={15} />Lưu mật khẩu</button></div><div className="mt-6 border-t border-slate-100 pt-4"><h4 className="mb-3 font-bold text-slate-700">Cài đặt thông báo</h4><button type="button" className="flex cursor-pointer items-center gap-3 text-sm text-slate-600 active:scale-[0.98]"><span className="flex h-6 w-11 items-center rounded-full bg-brand p-0.5"><span className="h-5 w-5 rounded-full bg-white" /></span>Nhận SMS khi có ca Cấp cứu / Hội chẩn</button></div><button type="button" className="mt-10 inline-flex w-full cursor-pointer items-center justify-center gap-2 rounded-md border border-rose-200 bg-rose-50 px-4 py-2 text-sm font-bold text-rose-600 transition hover:bg-rose-100 active:scale-[0.98]"><LogOut size={15} />Đăng xuất</button></article>
        <article className="panel"><div className="mb-4 flex items-center justify-between"><h3 className="text-base font-bold text-slate-800">Lịch trực tuần này</h3><span className="text-xs font-bold text-brand">10/05 - 16/05</span></div><div className="space-y-3">{[['Thứ 2 (10/05) - Ca Sáng', '08:00 - 12:00 | Phòng khám 202', 'brand'], ['Thứ 3 (11/05) - Ca Sáng', '08:00 - 12:00 | Phòng khám 202', 'brand'], ['Thứ 5 (13/05) - Ca Chiều (Trực thay)', '13:00 - 17:00 | Phòng khám 205', 'amber']].map(([title, time, tone]) => <button key={title} type="button" className={`w-full cursor-pointer rounded-md border px-4 py-3 text-left transition hover:shadow-sm active:scale-[0.99] ${tone === 'amber' ? 'border-amber-200 bg-amber-50 text-amber-700' : 'border-sky-200 bg-sky-50 text-brand'}`}><p className="font-bold">{title}</p><p className="mt-1 text-sm text-slate-600">{time}</p></button>)}</div><button type="button" className="mt-5 w-full cursor-pointer rounded-md border border-dashed border-slate-300 px-4 py-2 text-sm font-bold text-slate-500 transition hover:border-brand hover:text-brand active:scale-[0.98]">Xem lịch tháng tới</button></article>
      </section>
    </div>
  );
}
