import { Paperclip, Send } from 'lucide-react';
import { SearchInput } from '../components/shared';

const queue = [
  { code: 'PA-015', name: 'Trần Đình C.', tag: 'Khẩn cấp', time: '5p trước', preview: 'Sốt cao 39 độ, khó thở nhẹ...', active: true },
  { code: 'PA-019', name: 'Lê Tuấn Anh', tag: 'Bình thường', time: '15p trước', preview: 'Đau họng, cần mua thuốc...', active: false },
];

export default function ConsultationView({ onNotify }: { onNotify: (message: string) => void }) {
  return (
    <div className="grid min-h-[680px] gap-4 xl:grid-cols-[0.8fr_1.35fr_0.85fr]">
      <aside className="rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><h2 className="panel-title">Ca chờ tư vấn (3)</h2><div className="mt-3"><SearchInput placeholder="Tìm kiếm..." /></div><div className="mt-3 space-y-2">{queue.map((item) => <button key={item.code} type="button" className={`w-full cursor-pointer rounded-md border p-3 text-left transition hover:border-brand active:scale-[0.99] ${item.active ? 'border-sky-100 bg-sky-50' : 'border-slate-200 bg-white'}`}><div className="flex justify-between gap-2"><b className="text-slate-800">{item.name}</b><span className="text-xs text-slate-400">{item.time}</span></div><span className={`mt-1 inline-flex rounded px-2 py-0.5 text-xs font-bold ${item.tag === 'Khẩn cấp' ? 'bg-rose-100 text-rose-600' : 'bg-slate-100 text-slate-500'}`}>{item.tag}</span><p className="mt-1 truncate text-xs text-slate-500">{item.preview}</p></button>)}</div></aside>
      <section className="flex flex-col rounded-lg border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-200 px-4 py-3"><div className="flex items-center gap-3"><span className="h-8 w-8 rounded-full bg-slate-200" /><div><p className="font-bold text-slate-800">Trần Đình C.</p><p className="text-xs font-medium text-emerald-600">Đang trực tuyến</p></div></div><button type="button" onClick={() => onNotify('Đã kết thúc ca tư vấn')} className="cursor-pointer rounded-md border border-rose-200 px-3 py-1.5 text-xs font-bold text-rose-600 transition hover:bg-rose-50 active:scale-[0.98]">Kết thúc ca</button></div><div className="flex-1 space-y-4 p-4"><p className="mx-auto w-fit rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-500">Hệ thống: Ca tư vấn được chuyển giao từ AI Triage.</p><ChatBubble align="left" text="hê lô thở" time="14:05" /><ChatBubble align="right" text="thở bé xíu" time="14:07" /></div><div className="flex items-center gap-2 border-t border-slate-200 p-3"><button type="button" className="cursor-pointer text-slate-400 hover:text-brand active:scale-95" aria-label="Đính kèm"><Paperclip size={20} /></button><input className="form-input flex-1 rounded-full bg-slate-50" placeholder="Nhập tin nhắn tư vấn..." /><button type="button" onClick={() => onNotify('Đã gửi tin nhắn tư vấn')} className="flex h-9 w-9 cursor-pointer items-center justify-center rounded-full bg-brand text-white transition hover:bg-[#1f7fb9] active:scale-95" aria-label="Gửi"><Send size={17} /></button></div></section>
      <aside className="rounded-lg border border-slate-200 bg-white shadow-sm"><div className="border-b border-rose-100 bg-rose-50 px-4 py-3"><h3 className="font-bold text-rose-600">Tóm tắt từ Chatbot AI</h3></div><div className="space-y-4 p-4"><InfoBlock title="Triệu chứng chính:" lines={['Sốt 39 độ, không hạ.', 'Khó thở, thở khò khè.']} /><InfoBlock title="Đánh giá nguy cơ (AI):" badge="Cao (Khẩn cấp)" /><InfoBlock title="Tiền sử bệnh án:" lines={['Chưa có thông tin trên hệ thống.']} /><label className="block border-t border-slate-100 pt-4"><span className="mb-1.5 block text-sm font-medium text-slate-700">Ghi kết luận tư vấn</span><textarea className="form-textarea" placeholder="Ghi chú lâm sàng ngắn gọn..." /></label><button type="button" onClick={() => onNotify('Đã yêu cầu bệnh nhân đặt lịch khám')} className="secondary-action w-full cursor-pointer active:scale-[0.98]">Yêu cầu Đặt lịch khám</button></div></aside>
    </div>
  );
}

function ChatBubble({ align, text, time }: { align: 'left' | 'right'; text: string; time: string }) { const right = align === 'right'; return <div className={`flex ${right ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[68%] rounded-lg px-4 py-3 text-sm ${right ? 'bg-brand text-white' : 'bg-slate-100 text-slate-600'}`}><p>{text}</p><p className={`mt-2 text-right text-xs ${right ? 'text-white/70' : 'text-slate-400'}`}>{time}</p></div></div>; }
function InfoBlock({ title, lines, badge }: { title: string; lines?: string[]; badge?: string }) { return <div><h4 className="mb-2 text-sm font-bold text-slate-700">{title}</h4>{badge ? <span className="rounded bg-rose-50 px-2 py-1 text-xs font-bold text-rose-600">{badge}</span> : null}{lines ? <div className="space-y-1 text-sm text-slate-600">{lines.map((line) => <p key={line}>- {line}</p>)}</div> : null}</div>; }
